<?php

declare(strict_types=1);

namespace Jolicode\WalletKit\Pass\Android\Model\Generic;

/**
 * @phpstan-type GenericType 'GENERIC_TYPE_UNSPECIFIED'|'GENERIC_SEASON_PASS'|'GENERIC_UTILITY_BILLS'|'GENERIC_PARKING_PASS'|'GENERIC_VOUCHER'|'GENERIC_GYM_MEMBERSHIP'|'GENERIC_LIBRARY_MEMBERSHIP'|'GENERIC_RESERVATIONS'|'GENERIC_AUTO_INSURANCE'|'GENERIC_HOME_INSURANCE'|'GENERIC_ENTRY_TICKET'|'GENERIC_RECEIPT'|'GENERIC_LOYALTY_CARD'|'GENERIC_OTHER'
 */
enum GenericTypeEnum: string
{
    case UNSPECIFIED = 'GENERIC_TYPE_UNSPECIFIED';
    case SEASON_PASS = 'GENERIC_SEASON_PASS';
    case UTILITY_BILLS = 'GENERIC_UTILITY_BILLS';
    case PARKING_PASS = 'GENERIC_PARKING_PASS';
    case VOUCHER = 'GENERIC_VOUCHER';
    case GYM_MEMBERSHIP = 'GENERIC_GYM_MEMBERSHIP';
    case LIBRARY_MEMBERSHIP = 'GENERIC_LIBRARY_MEMBERSHIP';
    case RESERVATIONS = 'GENERIC_RESERVATIONS';
    case AUTO_INSURANCE = 'GENERIC_AUTO_INSURANCE';
    case HOME_INSURANCE = 'GENERIC_HOME_INSURANCE';
    case ENTRY_TICKET = 'GENERIC_ENTRY_TICKET';
    case RECEIPT = 'GENERIC_RECEIPT';
    case LOYALTY_CARD = 'GENERIC_LOYALTY_CARD';
    case OTHER = 'GENERIC_OTHER';
}
